"""Gate: the README Quickstart must match what the code actually prints.

The 0.1.0 README quoted ``9.5775%`` / ``8.0775%`` for a quickstart that
actually produces ``9.8250%`` / ``8.5750%``. The figures had been
hand-transcribed. They are now generated by ``scripts/gen_readme.py`` from
``examples/quickstart.py``, and this gate re-runs that generator in
``--check`` mode so any drift between the code, its output and the README
turns the suite red.
"""

import os
import subprocess
import sys

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GENERATOR = os.path.join(REPO_ROOT, "scripts", "gen_readme.py")
README = os.path.join(REPO_ROOT, "README.md")
EXAMPLE = os.path.join(REPO_ROOT, "examples", "quickstart.py")


def _env():
    env = dict(os.environ)
    env["PYTHONPATH"] = REPO_ROOT + os.pathsep + env.get("PYTHONPATH", "")
    return env


needs_sources = pytest.mark.skipif(
    not (os.path.exists(GENERATOR) and os.path.exists(EXAMPLE)),
    reason="generator/example not present (installed-package layout)",
)


@needs_sources
def test_example_script_runs_clean():
    proc = subprocess.run(
        [sys.executable, EXAMPLE],
        cwd=REPO_ROOT,
        env=_env(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    assert proc.returncode == 0, proc.stderr.decode("utf-8", "replace")
    assert proc.stdout.strip(), "quickstart produced no output"


@needs_sources
def test_readme_quickstart_is_not_stale():
    proc = subprocess.run(
        [sys.executable, GENERATOR, "--check"],
        cwd=REPO_ROOT,
        env=_env(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    assert proc.returncode == 0, (
        "README.md Quickstart is out of date. Run "
        "`python3 scripts/gen_readme.py`.\n"
        + proc.stdout.decode("utf-8", "replace")
        + proc.stderr.decode("utf-8", "replace")
    )


@needs_sources
def test_readme_quotes_no_stale_rate_by_hand():
    """Every '%'-suffixed figure in the README must come from a generated
    region — none may be hand-typed prose.

    Derived: the set of generated regions is found by scanning the markers,
    never enumerated as a literal.
    """
    import re

    with open(README, encoding="utf-8") as fh:
        text = fh.read()

    generated_spans = []
    for m in re.finditer(
        r"<!-- BEGIN GENERATED: (?P<name>[\w-]+) -->(?P<body>.*?)"
        r"<!-- END GENERATED: (?P=name) -->",
        text,
        re.DOTALL,
    ):
        generated_spans.append((m.start(), m.end()))
    assert generated_spans, "README has no generated regions"

    def inside_generated(pos):
        return any(a <= pos < b for a, b in generated_spans)

    stray = [
        m.group(0)
        for m in re.finditer(r"\d+\.\d+%", text)
        if not inside_generated(m.start())
    ]
    assert not stray, (
        "hand-typed rate figures outside the generated regions: %r" % stray
    )
